### PR TITLE
fix: quick appointment uses the right context for appointment

### LINKED ISSUE #211: Remove calendar page

### PR DESCRIPTION
**Pull request by martiuh**
closes #234 
closes #211

### CODE REVIEW

File: src/components/Calendar/HeaderView/HeaderView.jsx [hunk 1]
```diff
@@ -144,14 +149,16 @@ const HeaderViewComponent = props => {
...
-              variant={"contained"}
-            >
-              CREATE APPOINTMENT
-            </Button>
+            <Tooltip placement="top" title={`${showCtrl ? "CTRL" : "⌘"} + B`}>
+              <Button
+                color="primary"
+                className={createButton}
+                onClick={modalForm.handleOnClickCreateMeeting(booking)}
+                variant={"contained"}
```
Comment (mishelashala) [inline src/components/Calendar/HeaderView/HeaderView.jsx]: no need for the curly braces:

```ts
variant={"contained"}

// equivalent
variant="contained"
```

**Review by mishelashala — CHANGES_REQUESTED** [review]

**Comment by martiuh** [comment]
@mishelashala I already made the changes.

**Review by mishelashala — APPROVED** [review]
