### PR TITLE
fix(Calendar): change the size of the calendar when the drawer opens …

### LINKED ISSUE #174: fix: calendar should resize
sidebar should not be floating, when it is visible the calendar resize

Screen Shot 2019-04-30 at 09 17 15

### PR DESCRIPTION
**Pull request by javiermijangosksquare**
Closes #174

### CODE REVIEW

File: src/pages/Calendar/CalendarPageLogic.js [hunk 1]
```diff
@@ -9,10 +9,26 @@ import { roomService } from "services";
...
   calendarContainer: {
     margin: "64px 5% 64px 5%"
+  },
+  contentShrink: {
+    transition: theme.transitions.create("margin-left", {
+      easing: theme.transitions.easing.easeOut,
+      duration: theme.transitions.duration.enteringScreen
+    }),
+    marginLeft: "36vw"
+    // marginLeft: "64px"
```
Comment (mishelashala) [inline src/pages/Calendar/CalendarPageLogic.js]: remove commented code
