### PR TITLE
Fix missing error in token for create/edit booking operations

### LINKED ISSUE #91: Missing token on create booking
When trying to create a new booking, the server responds that the token is missing from the request. You can't create bookings.

fail

### PR DESCRIPTION
**Pull request by basultobdKs**
The headers field in config object for fetch function had a bad name.

This fixs #91.

### CODE REVIEW

File: src/utils/sessionInfo.js [hunk 1]
```diff
@@ -1,14 +1,13 @@
 import { compose, prop, defaultTo } from "lodash/fp";
 
+const validateUserInfo = compose(defaultTo(""));
```
Comment (mishelashala) [inline src/utils/sessionInfo.js]: you don't need to use `compose`, the method is auto curried

```js
const validateUserInfo = defaultTo('');
```
