### PR TITLE
Bug/custom colors

### LINKED ISSUE #132: fix: add support for custom room colors

### PR DESCRIPTION
**Pull request by javiermijangosksquare**
Closes #132

### CODE REVIEW

File: src/components/BookingsSideBar/BookingList/BookingItem/BookingItem.jsx [hunk 1]
```diff
@@ -85,15 +85,21 @@ class BookingItemComponent extends React.Component {
       bookingDateGrid
     } = styleClasses;
 
-    const { userName, roomColor, roomNameAbbrev, dateText } = booking;
+    const { userName, roomColor, roomNameAbbrev, dateText, room } = booking;
+    const { bg_color: bgColor, txt_color: txtColor } = room;
```
Comment (mishelashala) [inline src/components/BookingsSideBar/BookingList/BookingItem/BookingItem.jsx]: `snake_case` only at dto level. Map them into `camelCase`

File: src/components/Calendar/Days/DaysView.jsx [hunk 2]
```diff
@@ -73,13 +72,13 @@ const customTimeSlotWrapper = ({ children }) =>
 
 const customEventWrapper = eventWrapper => {
   const { children, event } = eventWrapper;
-  const styles = getEventColors(event.color);
+  const { txt_color: txtColor, bg_color: bgColor } = event.booking.room;
```
Comment (mishelashala) [inline src/components/Calendar/Days/DaysView.jsx]: same here:

`snake_case` only at dto level. Map them into `camelCase`

File: src/components/Calendar/Events/EventToolTip/EventToolTip.jsx [hunk 3]
```diff
@@ -156,65 +65,46 @@ class EventToolTipComponent extends React.Component {
...
     } = styleClasses;
-    const { start, end, roomName, color } = content;
-    const bookingFormated = {
-      roomName,
-      dateText: getDateText(formatDate(start)),
-      startTime: formatTime(formatDate(start)),
-      endTime: formatTime(formatDate(end))
-    };
-    const tooltipStyleColors = getTooltipColor(color, styleClasses);
+    const { bg_color: bgColor, txt_color: txtColor } = content.booking.room;
```
Comment (mishelashala) [inline src/components/Calendar/Events/EventToolTip/EventToolTip.jsx]: same here

File: src/components/Calendar/Months/MonthsView.jsx [hunk 4]
```diff
@@ -31,13 +30,13 @@ const customDateCellWrapper = ({ children }) =>
 
 const customEventWrapper = eventWrapper => {
   const { children, event } = eventWrapper;
-  const styles = getEventColors(event.color);
+  const { txt_color: txtColor, bg_color: bgColor } = event.booking.room;
```
Comment (mishelashala) [inline src/components/Calendar/Months/MonthsView.jsx]: and here

File: src/components/Calendar/Weeks/WeeksView.jsx [hunk 5]
```diff
@@ -37,8 +36,8 @@ const customTimeSlotWrapper = ({ children }) =>
 
 const customEventWrapper = eventWrapper => {
   const { children, event } = eventWrapper;
-  const styles = getEventColors(event.color);
-  const { right, left } = getOffsets(event.color);
+  const { txt_color: txtColor, bg_color: bgColor } = event.booking.room;
```
Comment (mishelashala) [inline src/components/Calendar/Weeks/WeeksView.jsx]: and here

File: src/components/SnackBar/components/SnackBarSticker.jsx [hunk 6]
```diff
@@ -22,13 +22,17 @@ const style = theme => ({
...
+  txtColor,
   text,
   classes: { snackBarSticker, snackBarStickerContent }
 }) => {
   return (
-    <div className={snackBarSticker} style={{ background: `light${color}` }}>
-      <div className={snackBarStickerContent} style={{ color: `dark${color}` }}>
+    <div
+      className={snackBarSticker}
+      style={{ background: bgColor ? bgColor : "gray" }}
```
Comment (mishelashala) [inline src/components/SnackBar/components/SnackBarSticker.jsx]: avoid inline styles

File: src/components/SnackBar/components/SnackBarSticker.jsx [hunk 7]
```diff
@@ -22,13 +22,17 @@ const style = theme => ({
...
+    >
+      <div className={snackBarStickerContent} style={{ color: txtColor }}>
```
Comment (mishelashala) [inline src/components/SnackBar/components/SnackBarSticker.jsx]: avoid inline styles

File: src/mappers/bookingMapper.js [hunk 8]
```diff
@@ -123,11 +123,12 @@ export const mapToListFormat = booking => {
  */
 export const mapToNotificationContentFormat = ({ user, room }) => {
   const { name: userName } = user;
-  const { color, name: roomName } = room;
+  const { bg_color: bgColor, txt_color: txtColor, name: roomName } = room;
```
Comment (mishelashala) [inline src/mappers/bookingMapper.js]: and here

File: src/utils/OffSets.js [hunk 9]
```diff
@@ -1,11 +1,11 @@
-export const getOffsets = eventColor => {
-  switch (eventColor) {
-    case "green":
+export const getOffsets = eventIsRight => {
+  switch (eventIsRight) {
```
Comment (mishelashala) [inline src/utils/OffSets.js]: just use a ternary

File: src/utils/OffSets.js [hunk 10]
```diff
@@ -1,16 +1,11 @@
...
-      return {
+  return eventIsRight
+    ? {
         left: "unset",
         right: "0%"
-      };
-    case false:
-      return {
+      }
+    : {
```
Comment (mishelashala) [inline src/utils/OffSets.js]: replace object by factory function

```js
return eventIsRight ? rightStyles() : leftStyles();
```
