### PR TITLE
fix(Calendar): redirect to login if invalid token

### LINKED ISSUE #222: [Bug] Token expired
At the token expiration and receiving a 401 code from the server the data about the token it's not getting cleared, resulting in an error page and no obvious way of being able to use the app.

image

There should be a system in place that in case of a 401 that it's related to token expiration the local storage get's cleared.

### PR DESCRIPTION
**Pull request by martiuh**
If webtoken verification fails runs logout function and redirect to login.

Closes #222

### CODE REVIEW

File: src/pages/Room/CalendarContainer.jsx [hunk 1]
```diff
@@ -30,7 +36,15 @@ class CalendarContainerComponent extends React.Component {
         const { bookings: bookingsData } = data;
         this.setState({ bookingsData, allBookingsData, isServerDown: false });
       } else {
-        this.setState({ isServerDown: true });
+        console.error({ CalendarError: data });
```
Comment (mishelashala) [inline src/pages/Room/CalendarContainer.jsx]: delete logs

File: src/pages/Room/CalendarContainer.jsx [hunk 2]
```diff
@@ -73,4 +85,6 @@ class CalendarContainerComponent extends React.Component {
   }
 }
 
-export const CalendarContainer = withRouter(CalendarContainerComponent);
+export const CalendarContainer = withRouter(
```
Comment (mishelashala) [inline src/pages/Room/CalendarContainer.jsx]: use `compose` from `lodash/fp`

```jsx
export const compose(withRouter, withAuthContext)(CalendarContainerComponent)
```

**Comment by martiuh** [comment]
I just made the requested changes
